[general]
[window]
padding = { x = 1, y = 0 }
dynamic_padding = true

[font]
normal = { family = "FiraCode Nerd Font", style = "Regular" }
bold = { family = "FiraCode Nerd Font", style = "Bold" }
italic = { family = "FiraCode Nerd Font", style = "Italic" }
bold_italic = { family = "FiraCode Nerd Font", style = "Bold Italic" }
size = 11

[cursor]
style.shape = "Beam"
style.blinking = "On"
blink_interval = 600
blink_timeout = 0
